# Try this out by first creating the secret:
# kubectl create secret -n bpfman docker-registry regcred --docker-server=quay.io --docker-username=bpfman-bytecode+bpfmancreds --docker-password=JOGZ3FA6A9L2297JAT4FFN6CJU87LKTIY6X1ZGKWJ0W0XLKY0KPT5YKTBBEAGSF5
apiVersion: bpfman.io/v1alpha1
kind: ClusterBpfApplication
metadata:
  labels:
    app.kubernetes.io/name: clusterbpfapplication
  name: xdp-pass-private-all-nodes
spec:
  nodeSelector: {}
  byteCode:
    image:
      imagePullSecret:
        name: regcred
        namespace: bpfman
      url: quay.io/bpfman-bytecode/xdp_pass_private:latest
  programs:
    - name: pass
      type: xdp
      xdpInfo:
        links:
          - interfaceSelector:
              primaryNodeInterface: true
            priority: 55
